name: Landing Integrity

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install linkinator
        run: npm i -g linkinator
      - name: Generate sitemap
        run: |
          npm i ts-node
          npx ts-node scripts/generate-sitemap.ts
      - name: Link check (site tree)
        run: |
          echo "Checking internal links..."
          linkinator file://$GITHUB_WORKSPACE/app --recurse --silent --skip '^(?!.*app).*' || true
      - name: Upload sitemap
        uses: actions/upload-artifact@v4
        with:
          name: sitemap
          path: public/sitemap.xml
