[build]
  base = "hookahplus-v2-"
  command = "cd hookahplus-v2- && npm ci --legacy-peer-deps && npm run build"
  publish = "hookahplus-v2-/.next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_BUILD_FROM_SOURCE = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

[build.processing]
  skip_processing = false

[[build.processing.css]]
  bundle = true
  minify = true

[[build.processing.js]]
  bundle = true
  minify = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force Netlify to use this configuration
[build.processing]
  skip_processing = false

[[build.processing.css]]
  bundle = true
  minify = true

[[build.processing.js]]
  bundle = true
  minify = true

# Override any dashboard settings
[build.environment]
  FORCE_CONFIG = "true"
