[build]
  base = "hookahplus-v2-"
  command = "npm install && npm run build"
  publish = "hookahplus-v2-/.next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
