[build]
  base = "hookahplus-v2-"
  command = "npm install && npm run build"
  publish = "hookahplus-v2-/.next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_BUILD_FROM_SOURCE = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
