[build]
command = "cd hookahplus-v2- && npm ci --legacy-peer-deps && npx next build"
publish = "hookahplus-v2-/.next"

[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--legacy-peer-deps"

# No plugins - manual build approach to avoid dependency issues
# The @netlify/blobs@10.0.9 dependency issue is caused by automatic plugin detection
