# Netlify configuration for HookahPlus deployment
[build]
base = "."
command = "npm ci --legacy-peer-deps && npm run build"
publish = "app/.next"

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--legacy-peer-deps"
