[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://hookahplus.net"

# Use the live preview URL for PR/preview builds
[context.deploy-preview.environment]
  NEXT_PUBLIC_SITE_URL = "${DEPLOY_PRIME_URL}"

[context.branch-deploy.environment]
  NEXT_PUBLIC_SITE_URL = "${DEPLOY_URL}"
