import { NextRequest, NextResponse } from 'next/server';
import { loadSetupSession } from '../../../../../lib/launchpad/session-manager';

/**
 * GET /api/launchpad/preview/checklist
 * Preview Week-1 Wins checklist for ManyChat
 * Requires token query parameter
 */
export async function GET(req: NextRequest) {
  try {
    const searchParams = req.nextUrl.searchParams;
    const token = searchParams.get('token');

    if (!token) {
      return NextResponse.json(
        { error: 'Token is required' },
        { status: 400 }
      );
    }

    // Load setup session
    const progress = await loadSetupSession(token);
    if (!progress) {
      return NextResponse.json(
        { error: 'Setup session not found or expired' },
        { status: 404 }
      );
    }

    const loungeName = progress.data.step1?.loungeName || 'Your Lounge';

    // Generate checklist
    const checklist = generateWeekOneChecklist(loungeName);

    return NextResponse.json({
      success: true,
      preview: true,
      checklist,
      message: 'Complete LaunchPad to activate your Week-1 Wins tracker.',
    });
  } catch (error: any) {
    console.error('[Preview Checklist] Error:', error);
    return NextResponse.json(
      { error: 'Failed to generate checklist' },
      { status: 500 }
    );
  }
}

/**
 * Generate Week-1 Wins checklist
 */
function generateWeekOneChecklist(loungeName: string): string {
  return `# Week-1 Wins Checklist

**${loungeName}** - Your First 7 Days with H+

## Day 1: Go Live ✅

- [ ] Complete LaunchPad setup
- [ ] Download and print QR codes
- [ ] Share Staff Playbook with team
- [ ] Test first session

## Days 2-7: Track Your Wins

### Comped Sessions Avoided
- [ ] Review comp policy settings
- [ ] Track sessions that would have been comped
- [ ] See savings in Week-1 Wins dashboard

### Add-ons Captured
- [ ] Staff adds extras during sessions
- [ ] Track coals, drinks, premium flavors
- [ ] Monitor add-on revenue

### Repeat Guests Recognized
- [ ] System remembers customer preferences
- [ ] Staff sees past orders
- [ ] Build customer loyalty

### Time Saved Per Shift
- [ ] Faster checkout with H+ memory
- [ ] Less time on shift handoff
- [ ] Quicker session management

---

## How to View Your Wins

1. Open H+ Dashboard
2. Look for "Week-1 Wins" card
3. Click to see detailed breakdown

**Goal:** See clear ROI within 7 days. If you don't, we'll help fix it.

---

*Generated by H+ LaunchPad*`;
}

