name: Conflict Marker Guard
on: [pull_request, push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail if merge conflict markers exist
        run: |
          if git grep -nE '^(<<<<<<<|=======|>>>>>>>)' -- .; then
            echo "Conflict markers present"
            exit 1
          fi
