layouts:
  - type: High Boy
    max_seats: 2
    notes: Ideal for fast turnover pairs
  - type: Sofa
    max_seats: 6
    notes: Good for mid-size groups, off-peak preferred
  - type: Sectional
    max_seats: 8
    notes: Typically booked for 3+ guests, higher loyalty trigger
  - type: Bar
    max_seats: 10
    notes: Used for overflow or solo sippers / couples
personas:
  - name: Kayla
    type: Beginner
    visit_freq: 3x/wk
    loyalty_profile: Trying new flavors
    refill_sensitivity: High
  - name: Darnell
    type: Socialite
    visit_freq: 1x/wk
    loyalty_profile: Brings friends
    refill_sensitivity: Medium
  - name: Zay
    type: Pro
    visit_freq: Daily
    loyalty_profile: Loyal, always same mix
    refill_sensitivity: Low
staff:
  count: 1
  shift_minutes: 360
  table_turnover_minutes: 45
  max_sessions_per_table: 8
sessions:
  - section: Red Sofa
    seats: 6
    participants:
      - Kayla
      - Zay
      - Guest
    time: 18:30
    flavors:
      - Peach
      - Grape
      - Mint
    duration_minutes: 48
    status: Refill Alert
    loyalty_delta:
      Zay: 3
      Kayla: 1
      Guest: 0.5
  - section: Back Sectional
    seats: 8
    participants:
      - Beginner
      - Beginner
      - Socialite
      - Socialite
      - Pro
    time: 16:00
    flavors:
      - Lemon
      - Mint
    duration_minutes: 50
    status: Burnout
    loyalty_delta:
      Pro: 3
      Beginner: 1
  - section: High Boy 2
    seats: 2
    participants:
      - Zay
    time: 19:45
    flavors:
      - Grape
    duration_minutes: 40
    status: Stable
    loyalty_delta:
      Zay: 3
  - section: Bar Area
    seats: dynamic
    participants: 5
    time: 19:00
    status: Whisper Prompt
    loyalty: Low
