/**
 * LaunchPad Staff Playbook Generator
 * 
 * Generates 1-page Staff Playbook PDF/HTML from LaunchPad config
 */

import { LoungeOpsConfig } from '../../types/launchpad';

export interface StaffPlaybookContent {
  html: string;
  markdown: string;
}

/**
 * Generate Staff Playbook content
 */
export function generateStaffPlaybook(
  config: LoungeOpsConfig,
  dashboardUrl?: string
): StaffPlaybookContent {
  const markdown = `# ${config.lounge_name} - Staff Quick Start

**Welcome to H+!** This is your 1-page guide to running sessions.

---

## 🚀 Quick Start

1. **Open H+ Dashboard:** ${dashboardUrl || 'https://hookahplus.net/dashboard'}
2. **Start a Session:** Click "New Session" → Select table → Enter customer details
3. **Track Time:** Timer starts automatically (if timed sessions)
4. **Add Items:** Click "Add Item" for flavors, mixes, add-ons
5. **End Session:** Click "End Session" → Process payment

---

## 📋 Session Rules

- **Session Type:** ${config.session_type === 'flat' ? 'Flat Fee' : 'Timed'}
- **Base Price:** $${config.base_session_price.toFixed(2)}
- **Grace Period:** ${config.grace_period_minutes} minutes
- **Extensions:** ${config.extension_policy === 'na' ? 'N/A (Flat-rate)' : config.extension_policy === 'auto' ? 'Auto-prompt' : 'Manual only'}
- **Comp Policy:** ${config.comp_policy_enabled ? 'Manager approval required' : 'Disabled'}

---

## 🎨 Flavors & Mixes

**Standard Flavors:**
${config.flavors.standard.map(f => `- ${f.name}${f.price ? ` ($${f.price.toFixed(2)})` : ''}`).join('\n')}

**Premium Flavors:**
${config.flavors.premium.map(f => `- ${f.name} ($${f.price.toFixed(2)})`).join('\n')}

---

## 💡 Key Features

- **Shift Handoff:** Notes carry forward between shifts
- **Memory:** System remembers repeat guests' preferences
- **Add-ons:** Track extras (coals, drinks, etc.)
- **POS Bridge:** ${config.pos_bridge.pos_type === 'none' ? 'Manual entry' : `Syncs with ${config.pos_bridge.pos_type}`}

---

## 🆘 Need Help?

- **Dashboard:** ${dashboardUrl || 'https://hookahplus.net/dashboard'}
- **Support:** Check dashboard for contact info
- **Quick Tips:** Hover over any button for tooltips

---

**Remember:** H+ runs above your POS. Sessions, memory, and loyalty live here. Payment stays in your POS.

*Generated by H+ LaunchPad*
`;

  // Convert markdown to HTML (simple version)
  const html = markdown
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^\*\*(.+?)\*\*/gm, '<strong>$1</strong>')
    .replace(/^---$/gm, '<hr>')
    .replace(/^(\d+)\. (.+)$/gm, '<p><strong>$1.</strong> $2</p>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/\n/g, '<br>\n');

  return {
    html: `<div style="font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">${html}</div>`,
    markdown,
  };
}

